name: Publish and deploy B21

on:
  push:
    tags:
      - server*

jobs:
  deploy-server:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Build B21
        run: |
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o b21 main.go

      - name: Copy server to VM
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          source: "./b21"
          target: "~/b21"

      - name: Server Setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          script: |
            cd ~/b21
            ./move.sh
